spring.application.name=pizzariaboamassa

# SQL Server Configuration

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pizzaria_boamassadb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@ITB123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Informações

# spring.jpa.hibernate.ddl-auto=
# none:   Banco de dados e tabelas devem ser criados com antecedência
# update: Banco de dados deve ser criado com antecedência, tabelas podem ser criadas com antecedência, as tabelas
#         serão atualizadas pelo model toda a vez que o mesmo for alterado
# create-drop: Banco de dados deve ser criado com antecedência, as tabelas serão criadas automaticamente pelo model,
#         entretanto, as tabelas serão excluídas toda a vez que o servidor for "desligado" (interrompido)
# create: Banco de dados deve ser criado com antecedência, quando o servidor carrega, as tabelas serão recriadas,
#         entretanto, quando o servidor é interrompido as tabelas permanecem

#  Exercício
#
#  Acessando o SQL Server...
#
# - Criar o banco de dados pizzariaboamassadb e a tebela usuario de acordo com o Model Entity

